# Generated by Django 4.2.5 on 2023-09-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_endpointdata_slack_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointdata',
            name='track',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
